name: "${projectName}"
description: Lightweight and efficient plugin to turn dirt into mud without using glass bottle. Save your time!
website: "${projectRepositoryUrl}"
main: "${projectGroup}.${projectName}"
version: "${projectVersion}"
author: "${projectAuthor}"
api-version: "${gameVersion}"

permissions:
  fastmud.command:
    description: "Allows you to see and use: /fastmud"
    default: op

  fastmud.command.reload:
    description: "Allows you to use: /fastmud reload"
    default: op

  fastmud.command.*:
    description: Allows you use any fastmud command
    default: op

    children:
      fastmud.command: true
      fastmud.command.reload: true

commands:
  fastmud:
      description: Manage fastmud plugin
      permission: fastmud.command
