name: "${projectName}"
description: Lightweight and efficient plugin to turn dirt into mud without using glass bottle. Save your time!
main: "${projectGroup}.${projectName}"
version: "${projectVersion}"
author: "${projectAuthor}"
api-version: "${gameVersion}"
